### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by GamingonTour1** [Cosmoverse/NoVPN#6]
Error: "Class 'cosmoverse\antivpn\AntiVPN' not found" (EXCEPTION) in "/home/globalPlugins/NoVPN/src/cosmicpe/novpn/Main" at line 18
 src/pocketmine/plugin/PluginBase(115): cosmicpe\novpn\Main->onEnable()
src/pocketmine/plugin/PluginManager(541): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
#2 src/pocketmine/Server(1783): pocketmine\plugin\PluginManager->enablePlugin(object cosmicpe\novpn\Main)
#3 src/pocketmine/Server(1769): pocketmine\Server->enablePlugin(object cosmicpe\novpn\Main)
#4 plugins/globalPlugins_v1.0.phar/src/xxAROX/Main(22): pocketmine\Server->enablePlugins(integer 1)
#5 src/pocketmine/plugin/PluginBase(115): xxAROX\Main->onEnable()
#6 src/pocketmine/plugin/PluginManager(541): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
#7 src/pocketmine/Server(1783): pocketmine\plugin\PluginManager->enablePlugin(object xxAROX\Main)
#8 src/pocketmine/Server(1769): pocketmine\Server->enablePlugin(object xxAROX\Main)
#9 src/pocketmine/Server(1582): pocketmine\Server->enablePlugins(integer 1)
#10 src/pocketmine/PocketMine(273): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[10] /home/cb1/, string[18] /home/cb1/plugins/)
 #11 src/pocketmine/PocketMine(296): pocketmine\server()
 #12 (11): require(string[62] phar:///home/cb1/pocketmine.phar/src/pocketmine/PocketMine.php)
[12:18:48] [Server thread/INFO]: Deaktiviere NoVPN v0.1.4
 Error: "Call to a member function close() on null" (EXCEPTION) in "/home/globalPlugins/NoVPN/src/cosmicpe/novpn/Main" at line 41
src/pocketmine/plugin/PluginBase(117): cosmicpe\novpn\Main->onDisable()
 #1 src/pocketmine/plugin/PluginManager(628): pocketmine\plugin\PluginBase->setEnabled(boolean )
#2 src/pocketmine/plugin/PluginManager(548): pocketmine\plugin\PluginManager->disablePlugin(object cosmicpe\novpn\Main)
#3 src/pocketmine/Server(1783): pocketmine\plugin\PluginManager->enablePlugin(object cosmicpe\novpn\Main)
#4 src/pocketmine/Server(1769): pocketmine\Server->enablePlugin(object cosmicpe\novpn\Main)
#5 plugins/globalPlugins_v1.0.phar/src/xxAROX/Main(22): pocketmine\Server->enablePlugins(integer 1)
#6 src/pocketmine/plugin/PluginBase(115): xxAROX\Main->onEnable()
#7 src/pocketmine/plugin/PluginManager(541): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
#8 src/pocketmine/Server(1783): pocketmine\plugin\PluginManager->enablePlugin(object xxAROX\Main)
 src/pocketmine/Server(1769): pocketmine\Server->enablePlugin(object xxAROX\Main)
#10 src/pocketmine/Server(1582): pocketmine\Server->enablePlugins(integer 1)
#11 src/pocketmine/PocketMine(273): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[10] /home/cb1/, string[18] /home/cb1/plugins/)
 #12 src/pocketmine/PocketMine(296): pocketmine\server()
#13 (11): require(string[62] phar:///home/cb1/pocketmine.phar/src/pocketmine/PocketMine.php)

**Comment by Muqsit** [comment]
Download the phar from poggit, or if you want to run from source directly you must also download DEVirion and install the AntiVPN virion in the virions/ folder
